# Generated by Django 2.0.2 on 2018-03-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_auto_20180305_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='first_name',
            field=models.CharField(default='Anwar', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='last_name',
            field=models.CharField(default='Als', max_length=200),
            preserve_default=False,
        ),
    ]
