# Generated by Django 2.0.2 on 2018-02-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('event_type', models.TextField()),
                ('content', models.TextField()),
                ('location_url', models.URLField()),
                ('location_name', models.CharField(max_length=400)),
                ('picture', models.ImageField(blank=True, upload_to='event_pictures')),
            ],
        ),
    ]
