# Generated by Django 2.0.2 on 2018-02-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20180228_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='types',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
