# Generated by Django 2.0.2 on 2018-02-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_auto_20180228_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='types',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
