# Generated by Django 2.0.2 on 2018-03-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_auto_20180307_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='maximum_attendees',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='remaining_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
