# Generated by Django 2.0.2 on 2018-03-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0010_auto_20180312_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='seats_taken',
            new_name='seats_remaining',
        ),
    ]
