# Generated by Django 2.0.2 on 2018-03-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20180305_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_profile',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='individual_profile',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='individual_profile',
            name='interest',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='individual_profile',
            name='my_website',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='orginization_profile',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orginization_profile',
            name='location_URL',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='orginization_profile',
            name='location_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orginization_profile',
            name='my_website',
            field=models.URLField(),
        ),
    ]
