# Generated by Django 2.0.2 on 2018-03-05 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0004_auto_20180305_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('interest', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrginizationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('location_URL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('profile_type', models.CharField(choices=[('I', 'individual'), ('O', 'orginization')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='individual_profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orginization_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Individual_Profile',
        ),
        migrations.DeleteModel(
            name='Orginization_Profile',
        ),
    ]
