# Generated by Django 2.0.2 on 2018-03-05 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20180305_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orginizationprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='profile_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_profile.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orginizationprofile',
            name='profile_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_profile.Profile'),
            preserve_default=False,
        ),
    ]
