# Generated by Django 2.0.2 on 2018-02-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180220_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Featured',
            new_name='featured',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='pic',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Title',
            new_name='title',
        ),
    ]
