# Generated by Django 2.0.2 on 2018-02-22 08:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20180221_1516'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('featured_articles', django.db.models.manager.Manager()),
            ],
        ),
    ]
