# Generated by Django 2.0.2 on 2018-02-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20180228_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, default='/static/img.png', upload_to='article_pictures'),
        ),
    ]
