# Generated by Django 2.0.2 on 2018-03-13 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0021_article_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fans',
            field=models.ManyToManyField(related_name='fav_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='fans_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
