# Generated by Django 2.0.2 on 2018-03-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20180307_1450'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
            ],
        ),
    ]
